### ISSUE TITLE
Received packet with illegal length 16576

### ISSUE THREAD

**Issue by MartyLake** [coddingtonbear/inthe.am#309] opened 2018-12-13 22:50 UTC
Hello,

I don't know what happened, but a while after switching to intheam on windows (git-sdk64 bash), I've got this error when I try to sync:
```
Received packet with illegal length 16576
Syncing with taskwarrior.intheam:53589

The specified session have has been invalidated for some reason
Sync failed. Could not connect to the Taskserver
```

Do you have any idea how to solve this ?
Best,

**Comment by coddingtonbear** [comment] 2018-12-16 03:31
This is a duplicate of #301; have a look at that thread to find some ideas!  Unfortunately, this is a problem in the taskserver itself, and you might have better luck checking-in with folks in #taskwarrior on Freenode for ideas.

**Closed by coddingtonbear** 2018-12-16 03:31 UTC
