### ISSUE TITLE
Attempting to sign up on inthe.am results in Server Error 500

### ISSUE THREAD

**Issue by gatlee** [coddingtonbear/inthe.am#293] opened 2018-05-26 06:25 UTC
Sorry if this isn't the place to bring up the issue but I have tried to sign up through the website with multiple browsers, user accounts and devices to sign up but they all result in Server Error 500. 

After selecting my account through google's interface it redirects and sends me to the error page with no additional information.

Thanks for the help

**Comment by DTV96Calibre** [comment] 2018-05-28 17:40
I'm also having this issue

**Comment by coddingtonbear** [comment] 2018-05-28 20:45
Not totally sure at the moment, but the error message I see in the logs make me wonder if it's this: https://github.com/omab/python-social-auth/issues/1033; I'm currently running a very old version of python-social-auth, so it might be that.  Looking into it now!

**Comment by coddingtonbear** [comment] 2018-05-28 21:04
Just upgraded to the latest version of `social-core` (the successor package to python-social-auth); I don't have a way of trying to reproduce this given that it does let me log-in, and I do still see accounts registering successfully.  Could one of you having trouble with this give it a shot again and let me know if you're able to log-in?

**Comment by dprn** [comment] 2018-05-28 21:06
I am still getting the same Server Error when I try to sign up.

**Comment by coddingtonbear** [comment] 2018-05-28 21:09
@dprn -- could you maybe give me a screenshot of the error you're seeing?

**Comment by dprn** [comment] 2018-05-28 21:10
<img width="929" alt="screen shot 2018-05-28 at 23 09 40" src="https://user-images.githubusercontent.com/3765467/40629560-4348d300-62cc-11e8-9613-1848d96b23d9.png">

not much info there, but I hope it helps

**Comment by coddingtonbear** [comment] 2018-05-28 21:19
Hrm; I see the error messages now.  It looks like the problem is actually that the inode table is full; looking into it now.

**Comment by coddingtonbear** [comment] 2018-05-28 22:08
That was a surprisingly complicated;  I think you should be OK now, though -- I've reformatted the partition holding task data such that it has a (much) higher inode ratio.  Let me know if that doesn't do it for you.

**Comment by gatlee** [comment] 2018-05-29 03:38
I will email you privately

**Comment by coddingtonbear** [comment] 2018-05-29 04:00
@gatlee / @xobs -- I just pushed up a little change to how account provisioning works; I'm not totally sure it'll help, but it'll at least work around an error message I found while reading through logs relating to these registrations.  Could one of you try registering again and let me know if you're able to do so now?

**Comment by xobs** [comment] 2018-05-29 04:01
Mine may be different, because it used to work and now it's not:

````sh
xobs@Cuboid:~/.task$ task sync
Syncing with taskwarrior.inthe.am:53589

Sync failed.  The Taskserver returned error: 500 Client sync key not found.
xobs@Cuboid:~/.task$
````

The error 500, and the fact that it's just started happening, is why I thought it might be related.

**Comment by coddingtonbear** [comment] 2018-05-29 04:06
Your message @xobs, is *not* related, if you e-mail me at support@inthe.am, I can walk you through how to resolve that separately from this issue.

**Comment by gatlee** [comment] 2018-05-29 04:17
Yes I am able to do so now. Thanks so much! 

Shall I close this or wait for others to confirm that it works for them too?

**Comment by coddingtonbear** [comment] 2018-05-29 04:34
I can close it; @xobs & I are talking through other channels about his account's problem.

Cheers & good luck!

**Closed by coddingtonbear** 2018-05-29 04:34 UTC
Labels: maybe fixed?

**Comment by bretwardjames** [comment] 2019-04-05 21:40
I am having this issue as of just now:

![image](https://user-images.githubusercontent.com/41160276/55657918-bab81e80-57b0-11e9-88ac-c5d057c98b9a.png)

Email address is bretwardjames@gmail.com.
