### ISSUE TITLE
task sync fails on new setup on Ubuntu

### ISSUE THREAD

**Issue by orsenthil** [coddingtonbear/inthe.am#310] opened 2019-01-05 00:45 UTC
I copied my credentials from inthe.am settings and when I do the `task sync`, it fails with the message:

```
 task sync
c: 1 Received packet with illegal length: 16592
Syncing with taskwarrior.inthe.am:53589

The specified session has been invalidated for some reason.
Sync failed.  Could not connect to the Taskserver.

```
* Any troubleshooting advice?

**Comment by coddingtonbear** [comment] 2019-01-05 01:35
I'm afraid not; you could check out the issue that this is a duplicate of -- #301, though, to see if there might be tips there.

I can letting you know that it's not likely to have anything to do with Ubuntu, though -- I'm running 18.04 on both computers I use (& one of them, I only installed it two weeks ago), and I've not encountered any synchronization issues.

**Closed by coddingtonbear** 2019-01-05 01:35 UTC
